script_file: apptainer exec --cleanenv --nv --bind /home/minibaevag/storage/res_guzel/easydock:/opt/easydock --bind /home/minibaevag/storage/res_guzel/carsidock/CarsiDock:/opt/CarsiDock --pwd /opt/easydock --env PYTHONPATH=/opt/easydock:/opt/CarsiDock --env LD_LIBRARY_PATH=/usr/local/lib:/app/openbabel/build/lib:/usr/lib:/lib /home/minibaevag/storage/res_guzel/carsidock/carsidock_v2.sif python -m easydock.carsidock_server

ligand_payload_type: smiles
ligand_payload_key: ligands_smiles
mol_block_key: mol_block

carsidock_repo: /opt/CarsiDock
pdb_file: /opt/CarsiDock/example_data/4YKQ_hsp90_40_water.pdb
sdf_file: /opt/CarsiDock/example_data/4YKQ_hsp90_40.sdf
output_dir: /opt/easydock/outputs/VH_no_zwitter
cuda_convert: true
device: cuda
num_threads: 1
num_conformer: 5
